### ISSUE TITLE
Question about subscribing

### ISSUE THREAD

**Issue by metsavaht** [hishnash/djangochannelsrestframework#1]
Hi. I have few questions about subscribers. As I understand pagination and filtering is not handled yet.

- Can I subscribe to all model changes that match permissions?
- How is unsubscribe handled?

Thank you for your input

**Comment by hishnash** [comment]
yes `pagination` is not supported yet.

for `filtering` in plain retrieve/list actions you can override the `filter_queryset(self, queryset: QuerySet, **kwargs)` method the `**kwargs` will be the top level values that you send in your upstream json. (not for subscribtion)

> Can I subscribe to all model changes that match permissions?

no at the moment the only action provided through mixins is `subscribe_instance` from `ObserverModelInstanceMixin` this lets you subscribe to changes on a given isntance not to a list/filter of items. 

eg you can subscribe to changes to user pk=4, but you cant subscribe to changes of all Users. 

Letting you subscribe to a given filter/queryset is absolutely something I would like to support, I will try to get some time over the next few days to create a branch with this support, what type of filtering would you like to be able to apple?

> How is unsubscribe handled?

Currently the websocket connection needs to be closed then the handers will be released.

**Comment by hishnash** [comment]
im more in favour of model mixin, if i do a little refactor a little how the `@generic_model_observer` works the place to do this would be in the `@handle_instance_change.groups` method so that for each set of filters you subscribe to it would create a distinct group (and the msg would be sent just to that group if and only if the Model Instance matched the filters).

> Unsubscribe might be also possible, need to look more into how subscriptions are remembered. Request id could be used to remove listeners from groups. Storing those in session might do it.

i just pused a work in progress branch for the unsub (possibly will put the other stuff in there as well) see https://github.com/hishnash/djangochannelsrestframework/pull/2. 

It however at the moment has one issue, if the instance that you have subscribed to is not longer there then you cant unsubscribe. (this if fine in the case were you sub to an increasing PK but not great if you sub to a slug that might be re-used).

> Storing those in session might do it.

channels 2 is implemented in such a way that each consumer instance is just used for one session so you can just store this stuff on `self` no need to put it into the session.

**Comment by hishnash** [comment]
> @handle_instance_change.groups method so that for each set of filters you subscribe to it would create a distinct group

Know i think about this it is not possible, it is important that `@handle_instance_change.groups` can run on any server so that the events are pushed and consumed on all servers that have subscribed.

**Comment by metsavaht** [comment]
> so instead what is needed maybe is a method on the consumer something like get_subscribed_requests_for_instance that yields back request_ids (of the subscribing requests) for the instance.

That could work. But doesn't it hurt scale-ability when more and more request ids are added? Maybe I misunderstood channels parts and need to brush of the knowledge.

**Comment by hishnash** [comment]
so what would be needed is a different Mixin like `ObserverModelInstanceMixin ` but `ObserverModeFilterMixin` this would have a different `@handle_instance_change.groups` that does not include the `pk` in the group name.

what this would mean is all consumers (that had subscribed) would get events for all updates yes this is not optimal at all. 

the other option is for the dev to write a custom `@handle_instance_change.groups` method for each consumer and here build the group ID based on the values that are in question (this would work if you are just filtering for == and the values can be stably converted into an ASCI string).

----
maybe some context is needed.

when an item is changed (updated, created, deleted) all of the `handle_instance_change.groups` methods on all the consumers for that item type are called, these methods yield back a list of strings that the message is pushed to. 

when you `subscribe` we also call this method and then bind this consumer to the returned groups. (so if any machine/worker on your cluster updates a model then its event will be picked up by all consumers that have subscribed to that given group string). 

---

an example group name for fixed known query types might be `{observer_uuid}-model-student-fields-{gender}`

this way then one could subscribe to all `female` student updates.
