### ISSUE TITLE
Is there a way to get an actions argument within of consumer methods?

### ISSUE THREAD

**Issue by ericel** [hishnash/djangochannelsrestframework#91]
Here is an example from the filtering model observer:
```
class MyConsumer(GenericAsyncAPIConsumer):
    ...

    @action()
    async def subscribe_to_comment_activity(self, user_pk, **kwargs):
        # We will check if the user is authenticated for subscribing.
        user = await database_sync_to_async(User.objects.get)(pk=user_pk)
        await self.comment_activity.subscribe(user=user)

```
I want to do some filtering, but that is only possible for my case if I have the instance at hand to filter against.
That means as I see it, I need the user=user value in the observer serializer method.

```
 @comment_activity.serializer
    def comment_activity(self, instance: Comment, action, **kwargs) -> CommentSerializer:
        '''This will return the comment serializer'''
        return CommentSerializer(instance)
```
And here comes my question then, how can I get the user value in the model serializer method?

**Comment by hishnash** [comment]
I think i should try to give some explication of how the subscription system works (i also need to figure out how to explain this better in the docs)


At its heart there are 2 parts to the subscription.

1) Happens when a change to a object takes place, this happens in that local thread on that server (you might have multiple server instance deployed). At this point model is serializered and sent to the channels backend. (this method is called once each time the object is changed indigently of if any one is subscribed or not). 

2) In the consumer instance that handles the WS connection the user subscribes to this these events. The method body of your `@model_observer` method is then called on that instance. (at this location you have access to `self`) i would suggested not overriding the `@comment_activity.serializer` but instead in your `@model_observer` reading the pk, looking up the instance and then calling the `CommentSerializer(instance).data` in there and sending the result.


Does this make any sense? i want to figure out a good way to explain this so i can put it in the docs.. i might need a diagram.

**Comment by ericel** [comment]
@hishnash  Makes a lot more sense now. I now have an idea of how to proceed. Thanks

**Comment by hishnash** [comment]
when you do `.subscribe(user=user)`  the user is being passed into the code that figures out what group to subscribe to. 


```
        @comment_activity.groups_for_signal
        def comment_activity(self, instance, **kwargs):
                for users in instance.mentioned:
                    yield f'user__{user.pk}'

        @comment_activity.groups_for_consumer
        def comment_activity(self, user, **kwargs):
                if user:
                        yield f'user__{user.pk}'
```   

The `groups_for_signal` method is called every time something changes (on the thread/server were the change is made) its job it to figure out what groups to send the message to.

The `groups_for_consumer` is called when you call `.subscribe` to figure out what groups to subscribe to.

Within your `@model_observer` method you can capture a the `group` kwarg will be equal to the group name the message was sent under you can use this to extract the info you need.

**Comment by hishnash** [comment]
if however each connection is obly eber going to subscribe to a single user then you can also save that user on self and read it back.

**Comment by ericel** [comment]
Thanks alot. This has really helped.!!
